name: Request
description: Do you have some feature request? Use this template
body:
  - type: markdown
    attributes:
      value: When creating a feature request, please be aware that we do not guarantee that your idea will be implemented. We are always working to make our software better, so please be pacient and do not put pressure on our devs.
  - type: textarea
    id: request
    attributes:
      label: Describe your idea
      description: Please provide enough information so we can understand and implement your idea
